# Generated by Django 4.2.3 on 2023-07-27 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
