# Generated by Django 4.2.3 on 2023-07-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_toy_alter_feeding_options_cat_toys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='toys',
        ),
        migrations.DeleteModel(
            name='Toy',
        ),
    ]
