# Generated by Django 4.2.3 on 2023-07-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_toy_cat_toys'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='color',
            field=models.CharField(default='no color', max_length=64),
        ),
        migrations.AddField(
            model_name='toy',
            name='name',
            field=models.CharField(default='no name', max_length=64),
        ),
    ]
